/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type TeamMember = {
  _id: string
  _type: 'team-member'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  title?: string
  phone?: string
  mail?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
  sortOrder?: number
}

export type TeamImage = {
  _id: string
  _type: 'team-image'
  _createdAt: string
  _updatedAt: string
  _rev: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  alt?: string
  title?: string
  description?: string
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
  paragraphs?: Array<{
    paragraphTitle?: string
    paragraph?: string
    _type: 'paragraphItem'
    _key: string
  }>
  sortOrder?: number
}

export type Schedule = {
  _id: string
  _type: 'schedule'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  date?: string
  content?: string
  location?: string
}

export type RoomImage = {
  _id: string
  _type: 'room-image'
  _createdAt: string
  _updatedAt: string
  _rev: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
}

export type Course = {
  _id: string
  _type: 'course'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  date?: string
  maxAttendees?: number
  location?: string
  price?: number
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  alt?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type ContactReasons = {
  _id: string
  _type: 'contact-reasons'
  _createdAt: string
  _updatedAt: string
  _rev: string
  reason?: string
}

export type Intro = {
  _id: string
  _type: 'intro'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
}

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | Slug
  | TeamMember
  | TeamImage
  | Service
  | Schedule
  | RoomImage
  | Course
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | ContactReasons
  | Intro
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ../rund-frau-next/src/sanity/queries.ts
// Variable: INTRO_QUERY
// Query: *[_type == "intro"][0]{  _id,  title,  description}
// export type INTRO_QUERYResult = {
//   _id: string
//   title: string | null
//   description: string | null
// } | null
// // Variable: COURSE_QUERY
// // Query: *[_type == "course"]{    _id,  title,  description,  date,  maxAttendees,  location,  price,  image{    asset->{url}  },  alt}
// export type COURSE_QUERYResult = Array<{
//   _id: string
//   title: string | null
//   description: string | null
//   date: string | null
//   maxAttendees: number | null
//   location: string | null
//   price: number | null
//   image: {
//     asset: {
//       url: string | null
//     } | null
//   } | null
//   alt: string | null
// }>
// // Variable: TEAM_MEMBERS_QUERY
// // Query: *[_type == "team-member"] | order(sortOrder asc){    _id,  name,  title,  phone,  mail,  image{    asset->{url}  },  description}
// export type TEAM_MEMBERS_QUERYResult = Array<{
//   _id: string
//   name: string | null
//   title: string | null
//   phone: string | null
//   mail: string | null
//   image: {
//     asset: {
//       url: string | null
//     } | null
//   } | null
//   description: string | null
// }>
// // Variable: SERVICE_QUERY
// // Query: *[_type == "service"] | order(sortOrder asc){    _id,  title,  description,}
// export type SERVICE_QUERYResult = Array<{
//   _id: string
//   title: string | null
//   description: string | null
// }>
// // Variable: SINGLE_SERVICE_QUERY
// // Query: *[_type == "service" && title == $title][0]{    _id,  title,  description,  image{    asset->{url}  },  paragraphs[],}
// export type SINGLE_SERVICE_QUERYResult = {
//   _id: string
//   title: string | null
//   description: string | null
//   image: {
//     asset: {
//       url: string | null
//     } | null
//   } | null
//   paragraphs: Array<{
//     paragraphTitle?: string
//     paragraph?: string
//     _type: 'paragraphItem'
//     _key: string
//   }> | null
// } | null
// // Variable: ROOMS_QUERY
// // Query: *[_type == "room-image"]{    _id,  image{    asset->{url}  },  alt,  caption,}
// export type ROOMS_QUERYResult = Array<{
//   _id: string
//   image: {
//     asset: {
//       url: string | null
//     } | null
//   } | null
//   alt: null
//   caption: null
// }>

// // Query TypeMap
// import '@sanity/client'
// declare module '@sanity/client' {
//   interface SanityQueries {
//     '*[_type == "intro"][0]{\n  _id,\n  title,\n  description\n}': INTRO_QUERYResult
//     '*[_type == "course"]{  \n  _id,\n  title,\n  description,\n  date,\n  maxAttendees,\n  location,\n  price,\n  image{\n    asset->{url}\n  },\n  alt\n}': COURSE_QUERYResult
//     '*[_type == "team-member"] | order(sortOrder asc){  \n  _id,\n  name,\n  title,\n  phone,\n  mail,\n  image{\n    asset->{url}\n  },\n  description\n}': TEAM_MEMBERS_QUERYResult
//     '*[_type == "service"] | order(sortOrder asc){  \n  _id,\n  title,\n  description,\n}': SERVICE_QUERYResult
//     '*[_type == "service" && title == $title][0]{\n    _id,\n  title,\n  description,\n  image{\n    asset->{url}\n  },\n  paragraphs[],\n}': SINGLE_SERVICE_QUERYResult
//     '*[_type == "room-image"]{  \n  _id,\n  image{\n    asset->{url}\n  },\n  alt,\n  caption,\n}': ROOMS_QUERYResult
//   }
// }
